apiVersion: v1
kind: Service
metadata:
  name: web-app-service
spec:
  type: NodePort
  selector:
    app: employees
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30000
