name: Build and Push to ECR

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        env:
          AWS_REGION: us-east-1
          ECR_REPO: webapp
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Create ECR repository (if not exists)
        run: |
            aws ecr describe-repositories --repository-names ${{ env.ECR_REPO }} || \
            aws ecr create-repository --repository-name ${{ env.ECR_REPO }}

      - name: Build, tag, and push webapp image
        run: |
          docker build -t webapp .
          docker tag webapp:latest ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY_WEBAPP }}:latest
          docker push ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY_WEBAPP }}:latest

